### PR TITLE
Implemented Semicolons

### PR DESCRIPTION
**Pull request by StuxSoftware**
Implements #55 
Untested though...

### CODE REVIEW

**Comment by StuxSoftware** [comment]
I just tested it -- It works.

**Comment by tusing** [comment]
Thanks. Will pull this into the VPS soon.

**Comment by StuxSoftware** [comment]
I just wonder what you mean with VPS?

**Comment by tusing** [comment]
Ah, the bot is running off of a free virtual private server from Amazon. I'll SSH into it and pull the changes soon.

**Comment by StuxSoftware** [comment]
Btw. I'm still writing code on an android device sshing into a private server.

**Comment by tusing** [comment]
Closed. Cool!

Do you program for a living, or just for fun? And how did you go about learning?

**Comment by StuxSoftware** [comment]
Well I'm still a student at my school in germany so... No, I don't program for a living.
And learning... Well that's a long story best discussed privately.

**Comment by StuxSoftware** [comment]
Do you have an IRC-Channel or some other means of chatting?

**Pull request merged**
