### PR TITLE
Added support for AO3

### PR DESCRIPTION
**Pull request by StuxSoftware**
Yay...
Usage: `linkao3(Crossovers that should not be)`

### CODE REVIEW

**Comment by tusing** [comment]
That...  that was fast!

_You're *awesome!*_

I was working on an AO3 implementation just now, but this is complete, and better! I'll work on DLP, now.

**Comment by StuxSoftware** [comment]
Fun fact:
I wrote this on a nix box over MOSH (a SSH alternative) on an android tablet and for the xpath I had a RDP connection to one of my windows servers.
That was shitty.

**Comment by tusing** [comment]
How... how do you even...

Teach me your ways. What have you done to gain these programming skills?

**Comment by StuxSoftware** [comment]
Be patient...
And have a bluetooth keyboard attached to it.

**Pull request merged**
