### PR TITLE
Revert "Allow non-ascii characters in story name"

### PR DESCRIPTION
**Pull request by tusing**
Doesn't work, unlike the previous one:

'''
Parsing submissions on SUBREDDIT  tusingtestfield
Parsing comment  cs56avu  in submission  39p3e7
FINDING:  {'ffn': ['Harry Potter and the Methods of Rationality\u200e\u200e']}
FFN requests:  ['Harry Potter and the Methods of Rationality\u200e\u200e']
ERROR:root:MAIN: AN EXCEPTION HAS OCCURED!
ERROR:root:!! Traceback (most recent call last):
!!   File "c:\Google Drive\Programming\reddit-ffn-bot\ffn_bot\reddit_bot.py", line 29, in __main__
    initialize()
!!   File "c:\Google Drive\Programming\reddit-ffn-bot\ffn_bot\reddit_bot.py", line 45, in initialize
    parse_submissions(r.get_subreddit(SUBREDDIT))
!!   File "c:\Google Drive\Programming\reddit-ffn-bot\ffn_bot\reddit_bot.py", line 128, in parse_submissions
    make_reply(comment, comment.id)
!!   File "c:\Google Drive\Programming\reddit-ffn-bot\ffn_bot\reddit_bot.py", line 135, in make_reply
    reply = formulate_reply(comment.body)
!!   File "c:\Google Drive\Programming\reddit-ffn-bot\ffn_bot\reddit_bot.py", line 157, in formulate_reply
    return parse_comment_requests(requests)
!!   File "c:\Google Drive\Programming\reddit-ffn-bot\ffn_bot\reddit_bot.py", line 164, in parse_comment_requests
    ffn_comment = fanfiction_parser.ffn_make_from_requests(ffn_requests)
!!   File "c:\Google Drive\Programming\reddit-ffn-bot\ffn_bot\fanfiction_parser.py", line 17, in ffn_make_from_requests
    found_ffn = ffn_comment_maker(ffn_link_finder(fic_requests))
!!   File "c:\Google Drive\Programming\reddit-ffn-bot\ffn_bot\fanfiction_parser.py", line 61, in ffn_comment_maker
    for link in links:
!!   File "c:\Google Drive\Programming\reddit-ffn-bot\ffn_bot\fanfiction_parser.py", line 52, in ffn_link_finder
    print("SEARCHING: ", search_request)
!!   File "c:\Anaconda3\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
!! UnicodeEncodeError: 'charmap' codec can't encode characters in position 66-67: character maps to <undefined>

SEARCHING:  A countdown timer is beginning. You can skip it by pressing a key.
Skipped at 9 seconds!
Complete!
Logging in...
Logged in.
Loaded CHECKED_COMMENTS.
Loading subreddits...
Adding user subreddits:  ['tusingtestfield']
ERROR:root:MAIN: AN EXCEPTION HAS OCCURED!
ERROR:root:!! Traceback (most recent call last):
!!   File "c:\Google Drive\Programming\reddit-ffn-bot\ffn_bot\reddit_bot.py", line 29, in __main__
    initialize()
!!   File "c:\Google Drive\Programming\reddit-ffn-bot\ffn_bot\reddit_bot.py", line 41, in initialize
    load_subreddits(bot_parameters)
!!   File "c:\Google Drive\Programming\reddit-ffn-bot\ffn_bot\reddit_bot.py", line 89, in load_subreddits
    SUBREDDIT_LIST.append(subreddit)
!! AttributeError: 'set' object has no attribute 'append'

A countdown timer is beginning. You can skip it by pressing a key.
Complete!
'''

### CODE REVIEW

**Comment by tusing** [comment]
It happened on [this](http://www.reddit.com/r/tusingtestfield/comments/39p3e7/lets_try_to_crash_it/) link. What should we change to fix this issue?

**Comment by StuxSoftware** [comment]
Which python version do you use

**Comment by StuxSoftware** [comment]
Look at
https://github.com/tusing/reddit-ffn-bot/blob/master/ffn_bot/reddit_bot.py#L94

**Comment by StuxSoftware** [comment]
And for the encoding: UTF8

**Pull request merged**
