### PR TITLE
Make stories distinct

### PR DESCRIPTION
**Pull request by StuxSoftware**
Ensure we have a distinct list of stories before we attempt to use link-only parsing to support cases
like "linkffn(<Link here>)"

### CODE REVIEW

**Comment by StuxSoftware** [comment]
I will resolve the merge conflicts.
I sense a bug in conjunction with #64 if we are not careful. (There was a specific case that I noticed when testing #64)

**Comment by tusing** [comment]
Thanks.

**Comment by StuxSoftware** [comment]
So, everything fixed, we can proceed.

**Comment by StuxSoftware** [comment]
I needed to make the urls the same for each story, so we parse the story url and generate one for ourselves.
To make it easier for me to remember which group is the story, I named the group containing the story id.

Btw: You can add comments to the lines in commit diffs and commits.

**Pull request merged**
