### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by StuxSoftware**
- Use generators to save memory.
- Use string joins to minimize overhead

### CODE REVIEW

**Comment by tusing** [comment]
Thanks!

**Comment by tusing** [comment]
Could you please go a bit more in-depth as to how the generators work in this context? I only have a vague idea right now.

**Comment by StuxSoftware** [comment]
Actually, I won't go more in depth with generators. Instead I will point you to a stack-overflow answer that will do quite nicely.
http://stackoverflow.com/a/231855

**Comment by tusing** [comment]
Awesome! Thank you.

**Comment by StuxSoftware** [comment]
So basically I replaced that list with a generator as
We basically only need to google the next link when we processed the previous one.
This is achieved by the for-loop on the generator. The for-loop internally calls the next function for each execution until it raises StopIteration. The function next causes the generator to resume the function body until it reaches the next yield-statement and returns the value passed to the yield. When the function exits without yielding anything, the next function raises StopIteration.

That means two things:
1. We actually throttle access to fanfiction.net (They are the one whe like to block bots, so we play nicely)
2. We don't need to cache the links of the comment.

**Comment by tusing** [comment]
That is really smart!

What do we do, though, if someone enters a search result that is incorrect in a series of correct ones? Say, if someone enters an invalid request (such that Google can't find any links for it) and then the remaining requests are all valid?

[In it's current state, the bot won't reply to anything](http://www.reddit.com/r/FanFiction/comments/39l4sv/hi_i_am_fanfictionbot_from_now_on_you_can_type/cs4stgl). Should we yield an empty string if no results are found?

**Comment by StuxSoftware** [comment]
Don't yield.
Only yield if there is a valid fanfiction

**Pull request merged**
