### PR TITLE
Fixed AO3 notes support

### PR DESCRIPTION
**Pull request by jimbo644664**
- Fixed logger class error.
- Improved support for AO3 summaries:
   - Fixed spacing issues in summaries due to AO3 allowing newlines;
   - Added dedicated handlers for AO3 notes without interfering with code for other archives;
   - Fixed escaping issue present with AO3 notes.
- Slight change to alignment in reddit_markdown.py for readability.

### CODE REVIEW

**Comment by StuxSoftware** [comment]
Can you split settings.yml from the pull-request. I have some problems wwith the rest but want to merge settings.yml now.

**Comment by StuxSoftware** [comment]
Can you remove the notes part — It was just an unneccessary byproduct of the xpath for ao3 summaries.

**Comment by StuxSoftware** [comment]
Can you reset ffn_bot/site.py and ffn_bot/reddit/reddit_environment.py

**Comment by jimbo644664** [comment]
- AO3 notes no longer appear in bot comment:
    - Associated code removed.

**Pull request merged**
